### ISSUE TITLE
[Feature Request] Privacy Policy

### ISSUE THREAD

**Issue by ngdenco** [willg101/blue-dot-replacement#2]
Since this requires "read and change all data on all websites you visit" permission, I would recommend having a privacy policy written and linked to in both the storepage and the app itself.

The potential use of this information is concerning, so having it written out as to why exactly the app needs this permission, and that it is not shared, sold, or used for other purposes would both put my mind at ease and also allow organizations to safely use the app.

**Comment by willg101** [comment]
What are your thoughts on this privacy policy:

# Privacy Policy

## What information is collected
The author of this project cares very much about your privacy, and for this very reason __does not incorporate any analytics into this extension__.

Further more, __no browsing history or personal information leaves the extension or is collected by its author__. _This excludes information that Google may collect automatically and/or which is outside the control of the author, such as installation/uninstallation statistics._

## Required permissions
The author realizes that some users may have concerns about this extension requiring the "read and change all data on all websites you visit" permission; however, it is crucial to note that this is a technical limitation of Google Chrome; without this permission, this extension would not be allowed to monitor tab title changes, and in turn, would not be able to do anything useful. In other words, this extension requires the "read and change all data on all websites you visit" permission because _more granular permissions like "read tab titles" and "change tab icons" **do not exist**_.

Being free and open source software, you are welcome, and even encouraged, to __read through the source code to verify this privacy policy__.

# Contact
If you have any questions about this Privacy Policy, please visit this extension's Github repository at https://github.com/willg101/blue-dot-replacement to open an issue or send the author a private message.

**Comment by ngdenco** [comment]
Fits exactly what I was looking for, if this was added as a link somewhere, such as below the "© 2018 Will Groenendyk." in the Options, it would fit all purposes from my end.

**Comment by willg101** [comment]
Great! I have created a [new release](https://github.com/willg101/blue-dot-replacement/releases/tag/1.3.0) that links to the [privacy policy](https://github.com/willg101/blue-dot-replacement/blob/1.3.0/PRIVACY%20POLICY.md), and have uploaded this to the Chrome Web Store; it should be available shortly.
